# Generated by Django 4.2.7 on 2023-11-11 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='collections',
            name='status',
        ),
    ]
