# Generated by Django 4.2.7 on 2023-11-06 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
    ]
