# Generated by Django 4.2.7 on 2023-11-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_remove_collections_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collections',
            name='status',
            field=models.CharField(blank=True, choices=[('Playing', 'Playing'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], max_length=10),
        ),
    ]
