# Generated by Django 4.2.7 on 2023-11-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_alter_games_options_alter_collections_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='images',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='games',
            name='release_date',
            field=models.DateField(max_length=255),
        ),
    ]
