# Generated by Django 4.2.7 on 2023-11-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_collections'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Completed',
        ),
    ]
