# Generated by Django 4.2.7 on 2023-11-27 02:59
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0003_alter_games_images_alter_games_release_date'),
    ]

    operations = [
        UnaccentExtension()
    ]
