# Generated by Django 4.2.7 on 2023-11-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0003_delete_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='status',
            field=models.CharField(choices=[('', 'Default'), ('Playing', 'Playing'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], default='', max_length=10),
        ),
    ]
