# Generated by Django 4.2.7 on 2023-11-11 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0004_ngames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nGames',
        ),
    ]
