# Generated by Django 4.2.7 on 2023-11-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0004_collections_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='status',
            field=models.CharField(choices=[(' ', 'Default'), ('Playing', 'Playing'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], default=' ', max_length=10),
        ),
    ]
