# Generated by Django 4.2.7 on 2023-11-11 21:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_delete_ngames'),
    ]

    operations = [
        migrations.CreateModel(
            name='nGames',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField(max_length=255)),
                ('team', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None), size=None)),
                ('esrb', models.CharField(choices=[('E', 'E'), ('E10+', 'E10'), ('T', 'T'), ('M', 'M'), ('NR', 'Norating')], default='NR', max_length=255)),
                ('platforms', models.CharField(max_length=255)),
                ('multiplayer', models.BooleanField()),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None), size=None)),
                ('images', models.CharField(max_length=255)),
                ('summary', models.TextField()),
            ],
            options={
                'db_table': 'ngames',
                'managed': True,
            },
        ),
    ]
