# Generated by Django 4.2.7 on 2023-11-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0006_alter_collections_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='status',
            field=models.CharField(blank=True, choices=[('Playing', 'Playing'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], max_length=10),
        ),
    ]
