# Generated by Django 4.2.7 on 2023-11-11 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0007_alter_ngames_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='games',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='baseApp.ngames'),
        ),
        migrations.DeleteModel(
            name='Games',
        ),
    ]
