# Generated by Django 4.2.7 on 2023-11-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0007_alter_collections_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
