# Generated by Django 4.2.7 on 2023-11-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0008_alter_collections_games_delete_games'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nGames',
            new_name='Games',
        ),
    ]
