# Generated by Django 4.2.7 on 2023-11-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0009_rename_ngames_games'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='games',
            table='games',
        ),
    ]
