# Generated by Django 4.2.7 on 2023-11-11 22:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0010_alter_games_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
    ]
