# Generated by Django 4.2.7 on 2023-11-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0011_alter_games_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='genres',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='games',
            name='team',
            field=models.CharField(max_length=255),
        ),
    ]
