# Generated by Django 4.2.7 on 2023-11-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0013_unaccent_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='status',
            field=models.CharField(blank=True, choices=[('Playing', 'Playing'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], max_length=10, null=True),
        ),
    ]
