# Generated by Django 4.2.7 on 2023-11-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_delete_completed_delete_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'completed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.CharField(db_column='Release Date', max_length=255)),
                ('team', models.CharField(max_length=255)),
                ('esrb', models.CharField(choices=[('E', 'E'), ('E10+', 'E10+'), ('T', 'T'), ('M', 'M'), ('NR', 'NR')], max_length=255)),
                ('platforms', models.CharField(max_length=255)),
                ('multiplayer', models.BooleanField()),
                ('genres', models.CharField(max_length=255)),
                ('images', models.CharField(max_length=255)),
                ('summary', models.TextField()),
            ],
            options={
                'db_table': 'games',
                'managed': False,
            },
        ),
    ]
