# Generated by Django 4.2.6 on 2023-10-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.CharField(blank=True, db_column='Release Date', max_length=255, null=True)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('esrb', models.CharField(blank=True, max_length=255, null=True)),
                ('platforms', models.CharField(blank=True, max_length=255, null=True)),
                ('multiplayer', models.BooleanField(blank=True, null=True)),
                ('genres', models.CharField(blank=True, max_length=255, null=True)),
                ('images', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'games',
                'managed': False,
            },
        ),
    ]
