# Generated by Django 4.2.7 on 2023-11-06 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseApp', '0001_initial'),
        ('login', '0002_delete_completed_delete_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='login.authuser')),
                ('games', models.ManyToManyField(to='baseApp.games')),
            ],
            options={
                'verbose_name_plural': 'Collections',
                'db_table': 'collections',
                'managed': True,
            },
        ),
    ]
