# Generated by Django 4.2.7 on 2023-11-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(default='', max_length=250)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
            options={
                'db_table': 'UserPage_userprofile',
                'managed': False,
            },
        ),
    ]
