# Generated by Django 4.2.7 on 2023-11-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0001_initial'),
        ('login', '0002_delete_completed_delete_games'),
        ('UserPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collections',
            new_name='Collection',
        ),
    ]
