# Generated by Django 4.2.7 on 2023-11-07 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collections',
        ),
    ]
