# Generated by Django 4.2.7 on 2023-11-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_completed_games'),
        ('UserPage', '0002_rename_collections_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='games',
            field=models.ManyToManyField(to='login.games'),
        ),
    ]
