# Generated by Django 4.2.7 on 2023-11-06 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_completed_games'),
        ('UserPage', '0003_alter_collection_games'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='Collections',
        ),
    ]
