# Generated by Django 4.2.7 on 2023-12-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPage', '0003_alter_userprofile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tset',
            field=models.TextField(default='', max_length=255),
        ),
    ]
